### ISSUE TITLE
fstab has hard coded device name for second drive

### ISSUE THREAD

**Issue by chrisred** [GNS3/gns3-vm#78]
I had no device /dev/sdb when i fired up the VM on my libvirt/kvm host, I use virtio so my drives ended up as /dev/vda1 /dev/vda2.

It booted but hung on the logo with no indication of the issue because it could not mount the second device from the fstab. Seems like that can be fixed by using the UUID for the second drive in the fstab, the boot drive already uses it.

eg.
UUID=af591248-2b45-4df4-8ff8-91e69d903f05 /opt  ext4  nodiratime  0  2

sudo blkid
/dev/vda1: UUID="1118793b-eb2f-4109-8fa9-2bd8bb35518f" TYPE="ext4"
/dev/vdb1: UUID="af591248-2b45-4df4-8ff8-91e69d903f05" TYPE="ext4"

**Comment by noplay** [comment]
How did you create the image for libvirt/kvm?

**Comment by chrisred** [comment]
Hi, i extracted the vmdk from the vbox .ova download (1.5.1)

**Comment by noplay** [comment]
Hi,

The VM is designed to be use in a specific environment with special tuning for that and the exact same hardware for everyone. Extracting the VMDK could work but we offer no warranty that it will not be break by an upgrade.

A solution could be to build a new image for KVM using the dedicated packer builder like what we do for VirtualBox and VMware but we will not do that because we don't have enough ressources for maintaining that (we need to rebuild the image for each release). Current VMs consume already too much time

You can start with an ubuntu server image and install GNS3 on it and using this instructions:
https://gns3.com/support/docs/install-on-a-remote-server

So you will be able to have all the flexibility you need
